name: deploy-eu-central-1-dev

on:
  workflow_dispatch:

jobs:
  deploy-eu-central-1-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run a one-line script
        run: |
          npm install
          npm --version
          ng build --configuration dev
          pipenv sync
          npx serverless --version
          npx serverless deploy --region eu-central-1 --stage dev
