name: deploy-eu-central-1-dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: npm install
      - name: cache dependencies
        uses: actions/cache@v2.1.7
        with:
            path: /
            key: cached_dependencies
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install angular CLI
        run: npm install -g @angular/cli@latest
      - name: build project
        run: ng build --configuration dev
      - name: cache build
        uses: actions/cache@v2.1.7
        with:
          path: dist
          key: cached_project_build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: deploy_frontend
        run: npx serverless deploy --region eu-central-1 --stage dev
  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
      - name: Sync to s3
        run: |
          npx serverless s3sync --region eu-central-1 --stage dev
          with:
            name: project_build
      
